DROP TABLE IF EXISTS "app"."recommendation_downweight";--> statement-breakpoint
CREATE TABLE "app"."recommendation_goodstuff" (
  "card_id" uuid PRIMARY KEY NOT NULL REFERENCES "catalog"."card"("id") ON DELETE CASCADE,
  "note" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint
CREATE TABLE "app"."recommendation_goodstuff_tag" (
  "card_id" uuid NOT NULL REFERENCES "app"."recommendation_goodstuff"("card_id") ON DELETE CASCADE,
  "tag" text NOT NULL,
  CONSTRAINT "recommendation_goodstuff_tag_pkey" PRIMARY KEY ("card_id", "tag"),
  CONSTRAINT "recommendation_goodstuff_tag_chk" CHECK (
    "tag" IN (
      'spot_removal',
      'interaction',
      'efficient',
      'flexible_removal',
      'board_wipe',
      'board_control',
      'cost_reduction',
      'modal',
      'protection',
      'board_protection',
      'instant_speed',
      'counterspell',
      'recursion',
      'reanimation',
      'ramp',
      'burst_mana',
      'mana_dork',
      'fixing',
      'land_ramp',
      'haste',
      'equipment',
      'card_selection',
      'value_engine',
      'card_advantage',
      'land_advantage',
      'land',
      'mana_engine',
      'mana_fixing',
      'utility_land',
      'removal',
      'channel',
      'fast_mana',
      'free_spell',
      'card_draw',
      'tax',
      'graveyard_hate',
      'theft',
      'punisher',
      'stax',
      'hatebear',
      'tutor_hate',
      'interaction_denial'
    )
  )
);--> statement-breakpoint
INSERT INTO "app"."recommendation_goodstuff" ("card_id")
SELECT c.id
FROM (
  VALUES
    ('Swords to Plowshares'),
    ('Path to Exile'),
    ('Generous Gift'),
    ('Beast Within'),
    ('Assassin''s Trophy'),
    ('Toxic Deluge'),
    ('Blasphemous Act'),
    ('Austere Command'),
    ('Heroic Intervention'),
    ('Counterspell'),
    ('Swan Song'),
    ('An Offer You Can''t Refuse'),
    ('Reanimate'),
    ('Dark Ritual'),
    ('Birds of Paradise'),
    ('Bloom Tender'),
    ('Farseek'),
    ('Nature''s Lore'),
    ('Three Visits'),
    ('Lightning Greaves'),
    ('Swiftfoot Boots'),
    ('Sensei''s Divining Top'),
    ('Land Tax'),
    ('Cabal Coffers'),
    ('Urborg, Tomb of Yawgmoth'),
    ('Boseiju, Who Endures'),
    ('Ancient Tomb'),
    ('Mana Drain'),
    ('Force of Will'),
    ('Force of Negation'),
    ('Mana Vault'),
    ('Chrome Mox'),
    ('Mox Diamond'),
    ('Jeska''s Will'),
    ('Necropotence'),
    ('Mystic Remora'),
    ('Sylvan Library'),
    ('Dauthi Voidwalker'),
    ('Orcish Bowmasters'),
    ('Opposition Agent'),
    ('Grand Abolisher')
) AS s(name)
JOIN "catalog"."card" c ON c.name = s.name
ON CONFLICT ("card_id") DO NOTHING;--> statement-breakpoint
INSERT INTO "app"."recommendation_goodstuff_tag" ("card_id", "tag")
SELECT c.id, t.tag
FROM (
  VALUES
    ('Swords to Plowshares', 'spot_removal'),
    ('Swords to Plowshares', 'interaction'),
    ('Swords to Plowshares', 'efficient'),
    ('Path to Exile', 'spot_removal'),
    ('Path to Exile', 'interaction'),
    ('Path to Exile', 'efficient'),
    ('Generous Gift', 'spot_removal'),
    ('Generous Gift', 'interaction'),
    ('Generous Gift', 'flexible_removal'),
    ('Beast Within', 'spot_removal'),
    ('Beast Within', 'interaction'),
    ('Beast Within', 'flexible_removal'),
    ('Assassin''s Trophy', 'spot_removal'),
    ('Assassin''s Trophy', 'interaction'),
    ('Assassin''s Trophy', 'flexible_removal'),
    ('Toxic Deluge', 'board_wipe'),
    ('Toxic Deluge', 'board_control'),
    ('Toxic Deluge', 'efficient'),
    ('Blasphemous Act', 'board_wipe'),
    ('Blasphemous Act', 'board_control'),
    ('Blasphemous Act', 'cost_reduction'),
    ('Austere Command', 'board_wipe'),
    ('Austere Command', 'board_control'),
    ('Austere Command', 'modal'),
    ('Austere Command', 'flexible_removal'),
    ('Heroic Intervention', 'protection'),
    ('Heroic Intervention', 'board_protection'),
    ('Heroic Intervention', 'instant_speed'),
    ('Counterspell', 'counterspell'),
    ('Counterspell', 'interaction'),
    ('Swan Song', 'counterspell'),
    ('Swan Song', 'interaction'),
    ('Swan Song', 'efficient'),
    ('An Offer You Can''t Refuse', 'counterspell'),
    ('An Offer You Can''t Refuse', 'interaction'),
    ('An Offer You Can''t Refuse', 'efficient'),
    ('Reanimate', 'recursion'),
    ('Reanimate', 'reanimation'),
    ('Reanimate', 'efficient'),
    ('Dark Ritual', 'ramp'),
    ('Dark Ritual', 'burst_mana'),
    ('Birds of Paradise', 'ramp'),
    ('Birds of Paradise', 'mana_dork'),
    ('Birds of Paradise', 'fixing'),
    ('Bloom Tender', 'ramp'),
    ('Bloom Tender', 'mana_dork'),
    ('Bloom Tender', 'fixing'),
    ('Farseek', 'ramp'),
    ('Farseek', 'land_ramp'),
    ('Farseek', 'fixing'),
    ('Nature''s Lore', 'ramp'),
    ('Nature''s Lore', 'land_ramp'),
    ('Nature''s Lore', 'fixing'),
    ('Three Visits', 'ramp'),
    ('Three Visits', 'land_ramp'),
    ('Three Visits', 'fixing'),
    ('Lightning Greaves', 'protection'),
    ('Lightning Greaves', 'haste'),
    ('Lightning Greaves', 'equipment'),
    ('Swiftfoot Boots', 'protection'),
    ('Swiftfoot Boots', 'haste'),
    ('Swiftfoot Boots', 'equipment'),
    ('Sensei''s Divining Top', 'card_selection'),
    ('Sensei''s Divining Top', 'value_engine'),
    ('Land Tax', 'card_advantage'),
    ('Land Tax', 'land_advantage'),
    ('Land Tax', 'value_engine'),
    ('Cabal Coffers', 'ramp'),
    ('Cabal Coffers', 'land'),
    ('Cabal Coffers', 'mana_engine'),
    ('Urborg, Tomb of Yawgmoth', 'mana_fixing'),
    ('Urborg, Tomb of Yawgmoth', 'land'),
    ('Urborg, Tomb of Yawgmoth', 'utility_land'),
    ('Boseiju, Who Endures', 'removal'),
    ('Boseiju, Who Endures', 'interaction'),
    ('Boseiju, Who Endures', 'utility_land'),
    ('Boseiju, Who Endures', 'channel'),
    ('Ancient Tomb', 'ramp'),
    ('Ancient Tomb', 'utility_land'),
    ('Ancient Tomb', 'fast_mana'),
    ('Mana Drain', 'counterspell'),
    ('Mana Drain', 'interaction'),
    ('Mana Drain', 'ramp'),
    ('Force of Will', 'counterspell'),
    ('Force of Will', 'interaction'),
    ('Force of Will', 'free_spell'),
    ('Force of Negation', 'counterspell'),
    ('Force of Negation', 'interaction'),
    ('Force of Negation', 'free_spell'),
    ('Mana Vault', 'ramp'),
    ('Mana Vault', 'fast_mana'),
    ('Chrome Mox', 'ramp'),
    ('Chrome Mox', 'fast_mana'),
    ('Mox Diamond', 'ramp'),
    ('Mox Diamond', 'fast_mana'),
    ('Jeska''s Will', 'ramp'),
    ('Jeska''s Will', 'burst_mana'),
    ('Jeska''s Will', 'card_advantage'),
    ('Necropotence', 'card_draw'),
    ('Necropotence', 'value_engine'),
    ('Mystic Remora', 'card_draw'),
    ('Mystic Remora', 'value_engine'),
    ('Mystic Remora', 'tax'),
    ('Sylvan Library', 'card_selection'),
    ('Sylvan Library', 'card_draw'),
    ('Sylvan Library', 'value_engine'),
    ('Dauthi Voidwalker', 'graveyard_hate'),
    ('Dauthi Voidwalker', 'value_engine'),
    ('Dauthi Voidwalker', 'theft'),
    ('Orcish Bowmasters', 'interaction'),
    ('Orcish Bowmasters', 'punisher'),
    ('Orcish Bowmasters', 'value_engine'),
    ('Opposition Agent', 'stax'),
    ('Opposition Agent', 'hatebear'),
    ('Opposition Agent', 'tutor_hate'),
    ('Opposition Agent', 'theft'),
    ('Grand Abolisher', 'protection'),
    ('Grand Abolisher', 'stax'),
    ('Grand Abolisher', 'interaction_denial')
) AS t(name, tag)
JOIN "catalog"."card" c ON c.name = t.name
JOIN "app"."recommendation_goodstuff" g ON g.card_id = c.id
ON CONFLICT ("card_id", "tag") DO NOTHING;
