export type ManaSymbol = {
  svgCode: string;
  english: string;
};

/** Snapshot of Scryfall /symbology. Key is the brace inner token (`T`, `W/U`). */
export const MANA_SYMBOLS: Record<string, ManaSymbol> = {
  '∞': { svgCode: 'INFINITY', english: 'infinite generic mana' },
  '0': { svgCode: '0', english: 'zero mana' },
  '1': { svgCode: '1', english: 'one generic mana' },
  '½': { svgCode: 'HALF', english: 'one-half generic mana' },
  '10': { svgCode: '10', english: 'ten generic mana' },
  '100': { svgCode: '100', english: 'one hundred generic mana' },
  '1000000': { svgCode: '1000000', english: 'one million generic mana' },
  '11': { svgCode: '11', english: 'eleven generic mana' },
  '12': { svgCode: '12', english: 'twelve generic mana' },
  '13': { svgCode: '13', english: 'thirteen generic mana' },
  '14': { svgCode: '14', english: 'fourteen generic mana' },
  '15': { svgCode: '15', english: 'fifteen generic mana' },
  '16': { svgCode: '16', english: 'sixteen generic mana' },
  '17': { svgCode: '17', english: 'seventeen generic mana' },
  '18': { svgCode: '18', english: 'eighteen generic mana' },
  '19': { svgCode: '19', english: 'nineteen generic mana' },
  '2': { svgCode: '2', english: 'two generic mana' },
  '2/B': { svgCode: '2B', english: 'two generic mana or one black mana' },
  '2/G': { svgCode: '2G', english: 'two generic mana or one green mana' },
  '2/R': { svgCode: '2R', english: 'two generic mana or one red mana' },
  '2/U': { svgCode: '2U', english: 'two generic mana or one blue mana' },
  '2/W': { svgCode: '2W', english: 'two generic mana or one white mana' },
  '20': { svgCode: '20', english: 'twenty generic mana' },
  '3': { svgCode: '3', english: 'three generic mana' },
  '4': { svgCode: '4', english: 'four generic mana' },
  '5': { svgCode: '5', english: 'five generic mana' },
  '6': { svgCode: '6', english: 'six generic mana' },
  '7': { svgCode: '7', english: 'seven generic mana' },
  '8': { svgCode: '8', english: 'eight generic mana' },
  '9': { svgCode: '9', english: 'nine generic mana' },
  A: { svgCode: 'A', english: 'an acorn counter' },
  B: { svgCode: 'B', english: 'one black mana' },
  'B/G': { svgCode: 'BG', english: 'one black or green mana' },
  'B/G/P': { svgCode: 'BGP', english: 'one black mana, one green mana, or 2 life' },
  'B/P': { svgCode: 'BP', english: 'one black mana or two life' },
  'B/R': { svgCode: 'BR', english: 'one black or red mana' },
  'B/R/P': { svgCode: 'BRP', english: 'one black mana, one red mana, or 2 life' },
  C: { svgCode: 'C', english: 'one colorless mana' },
  'C/B': { svgCode: 'CB', english: 'one colorless mana or one black mana' },
  'C/G': { svgCode: 'CG', english: 'one colorless mana or one green mana' },
  'C/P': { svgCode: 'CP', english: 'one colorless mana or two life' },
  'C/R': { svgCode: 'CR', english: 'one colorless mana or one red mana' },
  'C/U': { svgCode: 'CU', english: 'one colorless mana or one blue mana' },
  'C/W': { svgCode: 'CW', english: 'one colorless mana or one white mana' },
  CHAOS: { svgCode: 'CHAOS', english: 'chaos' },
  D: { svgCode: 'D', english: 'one potential land drop' },
  E: { svgCode: 'E', english: 'an energy counter' },
  G: { svgCode: 'G', english: 'one green mana' },
  'G/P': { svgCode: 'GP', english: 'one green mana or two life' },
  'G/U': { svgCode: 'GU', english: 'one green or blue mana' },
  'G/U/P': { svgCode: 'GUP', english: 'one green mana, one blue mana, or 2 life' },
  'G/W': { svgCode: 'GW', english: 'one green or white mana' },
  'G/W/P': { svgCode: 'GWP', english: 'one green mana, one white mana, or 2 life' },
  H: { svgCode: 'H', english: 'one colored mana or two life' },
  HR: { svgCode: 'HR', english: 'one-half red mana' },
  HW: { svgCode: 'HW', english: 'one-half white mana' },
  L: { svgCode: 'L', english: 'one mana from a legendary source' },
  P: { svgCode: 'P', english: 'modal budget pawprint' },
  PW: { svgCode: 'PW', english: 'planeswalker' },
  Q: { svgCode: 'Q', english: 'untap this permanent' },
  R: { svgCode: 'R', english: 'one red mana' },
  'R/G': { svgCode: 'RG', english: 'one red or green mana' },
  'R/G/P': { svgCode: 'RGP', english: 'one red mana, one green mana, or 2 life' },
  'R/P': { svgCode: 'RP', english: 'one red mana or two life' },
  'R/W': { svgCode: 'RW', english: 'one red or white mana' },
  'R/W/P': { svgCode: 'RWP', english: 'one red mana, one white mana, or 2 life' },
  S: { svgCode: 'S', english: 'one snow mana' },
  T: { svgCode: 'T', english: 'tap this permanent' },
  TK: { svgCode: 'TK', english: 'a ticket counter' },
  U: { svgCode: 'U', english: 'one blue mana' },
  'U/B': { svgCode: 'UB', english: 'one blue or black mana' },
  'U/B/P': { svgCode: 'UBP', english: 'one blue mana, one black mana, or 2 life' },
  'U/P': { svgCode: 'UP', english: 'one blue mana or two life' },
  'U/R': { svgCode: 'UR', english: 'one blue or red mana' },
  'U/R/P': { svgCode: 'URP', english: 'one blue mana, one red mana, or 2 life' },
  W: { svgCode: 'W', english: 'one white mana' },
  'W/B': { svgCode: 'WB', english: 'one white or black mana' },
  'W/B/P': { svgCode: 'WBP', english: 'one white mana, one black mana, or 2 life' },
  'W/P': { svgCode: 'WP', english: 'one white mana or two life' },
  'W/U': { svgCode: 'WU', english: 'one white or blue mana' },
  'W/U/P': { svgCode: 'WUP', english: 'one white mana, one blue mana, or 2 life' },
  X: { svgCode: 'X', english: 'X generic mana' },
  Y: { svgCode: 'Y', english: 'Y generic mana' },
  Z: { svgCode: 'Z', english: 'Z generic mana' },
};
